### ISSUE TITLE
Update Docs After zkEVM mainnet is live (TODO Dev Team)

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/astar-docs#608]
TODO Dev Team
- [x] Update RPC endpoint data here https://docs.astar.network/docs/build/zkEVM/quickstart#connecting-to-zkevm
- [x] Add note or update screenshots here  https://docs.astar.network/docs/build/zkEVM/bridge-to-zkevm
- [x] Update Faucet info to reflect zKatana (e.g. "Testnet Faucet" as no faucet for mainnet) https://docs.astar.network/docs/build/zkEVM/zkevm-faucet
- [x] Review if Node setup is feasible for DAC Validium (https://docs.astar.network/docs/build/zkEVM/zk-node/) - check with DevOps/Core team
- [x] Update Fee Calculation Example https://docs.astar.network/docs/build/zkEVM/fee

Marketing team should cover
- [] https://docs.astar.network/docs/build/zkEVM/faq/zkevm-general-faq
- [] https://docs.astar.network/docs/learn/zkEVM/faq
